name: Update README ⭐
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1.0.3
        with:
          userId: 2468629
          leaderboardId: 2333934
          sessionCookie: ${{ secrets.AOC_PRESENCE }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
